### ISSUE TITLE
bug: goroutine leak after turning on a session pool

### ISSUE THREAD

**Issue by pelageech** [ydb-platform/ydb-go-sdk#1455]
# Bug Report

**YDB GO SDK version:**
3.79.2

**Environment**
Ubuntu 20.04.6 LTS, amd64

**Current behavior:**
When it was updated a version of ydb-go-sdk from 3.77.0 to 3.79.2, we noticed that goroutines started leaking.
```
goroutine 78032 [select, 2287 minutes]:
bb.yandex-team.ru/cloud/cloud-go/vendor/google.golang.org/grpc.newClientStreamWithParams.func4()
        bb.yandex-team.ru/cloud/cloud-go/vendor/google.golang.org/grpc/stream.go:392 +0x8c
created by bb.yandex-team.ru/cloud/cloud-go/vendor/google.golang.org/grpc.newClientStreamWithParams in goroutine 78011
        bb.yandex-team.ru/cloud/cloud-go/vendor/google.golang.org/grpc/stream.go:391 +0xe08
```
I checked that there weren't any code changes in my repository. I suppose the problem is in SDK. Ofc, can be wrong.

**Expected behavior:**
No goroutine leak. 

**Steps to reproduce:**
Tbh I don't have any assuptions. But I'll try to investigate, too.

**Comment by pelageech** [comment]
I think it connected with https://github.com/ydb-platform/ydb-go-sdk/issues/1456
