### ISSUE TITLE
bug: SIGSEGV in Driver.Close

### ISSUE THREAD

**Issue by aizyurov** [ydb-platform/ydb-go-sdk#1585]
# Bug Report

**YDB GO SDK version:**

3.91.0

**Environment**

Linux 6.8.0-49-generic x86_64

**Current behavior:**

```
signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0x14146dd]
goroutine 10381 [running]:
github.com/ydb-platform/ydb-go-sdk/v3/internal/query.(*Client).Close(0x0, {0x2868700, 0xc000a41340})
/gopath/src/bb.yandex-team.ru/cloud/cloud-go/vendor/github.com/ydb-platform/ydb-go-sdk/v3/internal/query/client.go:188 +0x1d
github.com/ydb-platform/ydb-go-sdk/v3/internal/xsync.(*Once[...]).Close(0x2868da0, {0x2868700, 0xc000a41340})
/gopath/src/bb.yandex-team.ru/cloud/cloud-go/vendor/github.com/ydb-platform/ydb-go-sdk/v3/internal/xsync/once.go:44 +0x123
github.com/ydb-platform/ydb-go-sdk/v3.(*Driver).Close(0xc0023e7000, {0x2868700, 0xc000a41340})
/gopath/src/bb.yandex-team.ru/cloud/cloud-go/vendor/github.com/ydb-platform/ydb-go-sdk/v3/driver.go:190 +0x7dd
```

**Expected behavior:**

No error

**Steps to reproduce:**

Unknown. Happens from time to time

**Related code:**

**Other information:**

**Comment by asmyasnikov** [comment]
This situation can happens on closing driver twice
