### ISSUE TITLE
bug: panic: close of closed channel (`internal/cluster/Cluster.Close()`)

### ISSUE THREAD

**Issue by asmyasnikov** [ydb-platform/ydb-go-sdk#238]
# Bug Report

**YDB GO SDK version:**

v3.24.3-rc0

**Current behavior:**

```panic: close of closed channel

goroutine 546 [running]:
github.com/ydb-platform/ydb-go-sdk/v3/internal/cluster.(*Cluster).Close(0xc000826240, {0xe87938, 0xc0005a8180})
	/-S/vendor/github.com/ydb-platform/ydb-go-sdk/v3/internal/cluster/cluster.go:112 +0xb0
github.com/ydb-platform/ydb-go-sdk/v3/internal/router.(*router).clusterDiscovery(0xc000268200, {0xe87938, 0xc0005a8180})
	/-S/vendor/github.com/ydb-platform/ydb-go-sdk/v3/internal/router/router.go:77 +0x8d
github.com/ydb-platform/ydb-go-sdk/v3/internal/router.New.func2({0xe878c8, 0xc000b64000})
	/-S/vendor/github.com/ydb-platform/ydb-go-sdk/v3/internal/router/router.go:147 +0x65
github.com/ydb-platform/ydb-go-sdk/v3/internal/repeater.(*repeater).wakeUp(0xc000d44b40, {0xe88070, 0xc0003ef130}, {0xd65b7b, 0x5})
	/-S/vendor/github.com/ydb-platform/ydb-go-sdk/v3/internal/repeater/repeat.go:112 +0x1b9
github.com/ydb-platform/ydb-go-sdk/v3/internal/repeater.(*repeater).worker(0xc000d44b40, {0xe88070, 0xc0003ef130}, 0xc000e065c0)
	/-S/vendor/github.com/ydb-platform/ydb-go-sdk/v3/internal/repeater/repeat.go:136 +0x1d3
created by github.com/ydb-platform/ydb-go-sdk/v3/internal/repeater.New
	/-S/vendor/github.com/ydb-platform/ydb-go-sdk/v3/internal/repeater/repeat.go:80 +0x1e5```

**Comment by asmyasnikov** [comment]
Double closing of cluster occurs due to repeater works after Stop
