### ISSUE TITLE
bug: flaky test TestWorkerConcurrentStartAndClose

### ISSUE THREAD

**Issue by asmyasnikov** [ydb-platform/ydb-go-sdk#578]
https://github.com/ydb-platform/ydb-go-sdk/actions/runs/4176680680/jobs/7233292752#step:4:31

**Comment by rekby** [comment]
Test logs will drop in few days.

error for history:
```
go: downloading golang.org/x/text v0.3.3
ok  	github.com/ydb-platform/ydb-go-sdk/v3	5.414s	coverage: 12.6% of statements
ok  	github.com/ydb-platform/ydb-go-sdk/v3/balancers	1.070s	coverage: 88.4% of statements
?   	github.com/ydb-platform/ydb-go-sdk/v3/config	[no test files]
ok  	github.com/ydb-platform/ydb-go-sdk/v3/coordination	1.071s	coverage: 0.0% of statements [no tests to run]
?   	github.com/ydb-platform/ydb-go-sdk/v3/credentials	[no test files]
ok  	github.com/ydb-platform/ydb-go-sdk/v3/discovery	1.067s	coverage: 0.0% of statements [no tests to run]
?   	github.com/ydb-platform/ydb-go-sdk/v3/internal/allocator	[no test files]
--- FAIL: TestWorkerConcurrentStartAndClose (1.57s)
    worker_test.go:137: 
    panic.go:540: test run counter: 17
panic: Fail in goroutine after TestWorkerConcurrentStartAndClose has completed

goroutine 3021 [running]:
testing.(*common).Fail(0xc0000849c0)
	C:/hostedtoolcache/windows/go/1.19.5/x64/src/testing/testing.go:8[24](https://github.com/ydb-platform/ydb-go-sdk/actions/runs/4176680680/jobs/7233292752#step:4:25) +0x1a8
testing.(*common).Errorf(0xc0000849c0, {0xc96819, 0x3}, {0xc0005951e0, 0x1, 0x1})
	C:/hostedtoolcache/windows/go/1.19.5/x64/src/testing/testing.go:941 +0xaf
github.com/ydb-platform/ydb-go-sdk/v3/internal/xtest.(*testWrapper).Errorf(0xc000063770, {0xc96819, 0x3}, {0xc0005951e0, 0x1, 0x1})
	D:/a/ydb-go-sdk/ydb-go-sdk/internal/xtest/manytimes.go:103 +0xa5
github.com/stretchr/testify/assert.Fail({0x2850efa0, 0xc000063770}, {0xc00049c480, 0x53}, {0x0, 0x0, 0x0})
	C:/Users/runneradmin/go/pkg/mod/github.com/stretchr/testify@v1.7.1/assert/assertions.go:[26](https://github.com/ydb-platform/ydb-go-sdk/actions/runs/4176680680/jobs/7233292752#step:4:27)2 +0x438
github.com/stretchr/testify/assert.NoError({0x2850efa0, 0xc000063770}, {0xdaa600, 0xc0005950b0}, {0x0, 0x0, 0x0})
	C:/Users/runneradmin/go/pkg/mod/github.com/stretchr/testify@v1.7.1/assert/assertions.go:1334 +0x1[27](https://github.com/ydb-platform/ydb-go-sdk/actions/runs/4176680680/jobs/7233292752#step:4:28)
github.com/stretchr/testify/require.NoError({0x[28](https://github.com/ydb-platform/ydb-go-sdk/actions/runs/4176680680/jobs/7233292752#step:4:29)50ef58, 0xc00006[37](https://github.com/ydb-platform/ydb-go-sdk/actions/runs/4176680680/jobs/7233292752#step:4:38)70}, {0xdaa600, 0xc0005950b0}, {0x0, 0x0, 0x0})
	C:/Users/runneradmin/go/pkg/mod/github.com/stretchr/testify@v1.7.1/require/require.go:1261 +0xa5
github.com/ydb-platform/ydb-go-sdk/v3/internal/background.TestWorkerConcurrentStartAndClose.func1.1()
	D:/a/ydb-go-sdk/ydb-go-sdk/internal/background/worker_test.go:118 +0x1ab
created by github.com/ydb-platform/ydb-go-sdk/v3/internal/background.TestWorkerConcurrentStartAndClose.func1
	D:/a/ydb-go-sdk/ydb-go-sdk/internal/background/worker_test.go:111 +0x2fa
FAIL	github.com/ydb-platform/ydb-go-sdk/v3/internal/background	1.658s
```
